const ES = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'Error 404',
  Restaurant: 'Restaurante',
  Pages: 'Páginas',
  Contact: 'Contacto',
  in: 'en',
  Monday: 'Lunes',
  Tuesday: 'Martes',
  Wednesday: 'Miércoles',
  Thursday: 'Jueves',
  Friday: 'Viernes',
  Saturday: 'Sábado',
  Sunday: 'Domingo',
  Closed: 'Cerrado',
  'Opening hours': 'Horarios',
  'Order now': 'Ordenar ahora',
  Order: 'Ordenar',
  Book: 'Reservar',
  Delivery: 'Entrega',
  Booking: 'Reserva',
  'Order in delivery': 'Ordenar con entrega',
  'Order in Click & Collect': 'Ordenar en Click & Collect',
  'Our services': 'Nuestros servicios',
  'At {name}, we make online reservations easy: instant and without prior registration': 'En {name}, hacemos que las reservas en línea sean fáciles: instantáneas y sin registro previo',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': 'En {name}, preferimos el Click & Collect: sin registro, pago en línea o en el restaurante (tarjeta de crédito y vales de restaurante)',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': 'En {name}, entregamos en cualquier lugar de {city}: mismo precio que en el restaurante y sin cargo de servicio',
  'Book a table': 'Reservar una mesa',
  'Order and book online at {name}': 'Ordena y reserva en línea en {name}',
  'Language selection': 'Selección de idioma',
  'Theme selection': 'Selección de tema',
  'They talk about our restaurant {name} better than us': 'Hablan de nuestro restaurante {name} mejor que nosotros',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': 'En {name}, nos comprometemos a ofrecerte una experiencia culinaria auténtica e inolvidable. Esto es lo que algunos de nuestros clientes dijeron sobre su visita al restaurante en {formattedShortAddress}:',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': 'En el restaurante {name}, ofrecemos una amplia gama de servicios para que tu experiencia gastronómica sea aún más conveniente y placentera. Descubre nuestros servicios de entrega, Click & Collect y reservas en línea para aprovechar al máximo nuestro {formattedRestaurantType}, ya sea en casa o en nuestro establecimiento, pero siempre sin esperas.',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5 basado en {nbReviews} opiniones de Google',
  'Read more reviews': 'Leer más opiniones',
  Itinary: 'Itinerario',
  'Order / Book': 'Ordenar / Reservar',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': 'Descubre nuestro menú, disponible en el restaurante, en Click & Collect y en entrega a domicilio.',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': 'Puedes hacer tu pedido en Click & Collect o a domicilio directamente desde nuestro sitio web, ¡pruébalo!',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': '¡Bienvenido a {name}! Ven a descubrir nuestro {formattedRestaurantType} ubicado en {formattedShortAddress}! Nuestro restaurante ofrece cocina auténtica: ¡cocinamos platos caseros elaborados con productos frescos! Para facilitar tu visita, no dudes en reservar en línea. También puedes consultar nuestro menú en línea y realizar tu pedido ahora mismo: Click and Collect y entrega a domicilio',
  Home: 'Inicio',
  Contact: 'Contacto',
  'Click & Collect': 'Click & Collect',
  Delivery: 'Entrega',
  Menu: 'Menú',
  Book: 'Reservar',
  'Book at {name}': 'Reservar en {name}',
  'Book a table at {name}': 'Reservar una mesa en {name}',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': 'En {name}, un {formattedRestaurantType} en {formattedShortAddress}, te invitamos a reservar tu mesa en línea. Nuestro sistema de reservas es gratuito y no requiere registro. Reserva tu mesa en línea en {restaurantName} y ven a {formattedShortAddress2} para descubrir nuestro restaurante y nuestros platos auténticos',
  'Page not found': 'Página no encontrada',
  'Back to home page': 'Volver a la página de inicio',
  'Menu of {name}': 'Menú de {name}',
  'Discover the menu of {name}, {formattedRestaurantType}': 'Descubre el menú de {name}, {formattedRestaurantType}',
  '{name} Delivery': 'Entrega de {name}',
  'delivered to your home or office': 'entregado a tu hogar u oficina',
  'to go!': '¡para llevar!',
  '{name} food delivery': 'Entrega de comida de {name}',
  'Click & Collect {name}': 'Click & Collect {name}',
  'Have {name} delivered to you without service fees!': '¡Ten {name} entregado a tu domicilio sin cargos de servicio!',
  Fast: 'Rápido',
  'No registration': 'Sin registro',
  Economic: 'Económico',
  'No service fees': 'Sin cargos de servicio',
  Convenient: 'Conveniente',
  'Skip the line': 'Evita la cola',
  '{name} in Click & Collect': '{name} en Click & Collect',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': 'Nuestro sistema Click & Collect no requiere registro y puedes pagar en línea o en el restaurante, con tarjeta de crédito o vales de comida',
  'Order online at {name} with Click & Collect to save time!': '¡Ordena en línea en {name} con Click & Collect para ahorrar tiempo!',
  Cheap: 'Económico',
  'Same price as restaurant': 'Mismo precio que en el restaurante',
  Anywhere: 'En cualquier lugar',
  'Delivery in and around {city}': 'Entrega en {city} y sus alrededores',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': '¡Haz que te entreguen {name} al mismo precio que pagarías en un restaurante, gracias a Komdab',
  'Dishes at the same prices as à la carte and no service charges!': '¡Platos al mismo precio que en la carta y sin cargos de servicio!',
  of: 'de',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': 'Consulta el menú de {name} {formattedRestaurantType} en {formattedShortAddress}. Ordena para llevar con Click & Collect o a domicilio sin cargos de servicio',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': 'Reserva una mesa en línea en {name} {formattedRestaurantType} en {formattedShortAddress}. Reserva gratis en {name2} sin registro',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': '¡Haz que te entreguen {name} {formattedRestaurantType}! Entregas sin cargos de servicio, al mismo precio que en la carta, en todas partes de {city} y sus alrededores',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': 'Ordena con Click & Collect en {name} {formattedRestaurantType}. Sin cargos de servicio y sin registro. Paga en línea o en el restaurante en {formattedShortAddress}',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}, {formattedRestaurantType}, {formattedShortAddress}. Reserva y ordena con Click & Collect o entrega en nuestro sitio.',
  Address: 'Dirección',
  'Contact {name}': 'Contacta a {name}',
  '{name} is here to help!': '¡{name} está aquí para ayudar!',
  'First name': 'Nombre',
  'Last name': 'Apellido',
  'Phone number': 'Número de teléfono',
  Email: 'Email',
  Message: 'Mensaje',
  Error: 'Error',
  'First name is missing': 'Falta el nombre',
  'Last name is missing': 'Falta el apellido',
  'Email is invalid': 'El email no es válido',
  'Message is missing': 'Falta el mensaje',
  Send: 'Enviar',
  '{name} restaurant': 'Restaurante {name}',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': '¡Tu {formattedRestaurantType} {name} está listo para escuchar todas tus peticiones! Para información, solicitudes específicas, privatizaciones o servicios de catering, no dudes en enviarnos un mensaje y te responderemos lo antes posible!',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{formattedRestaurantTypeUpperFirst} en {city}',
  Sent: 'Enviado',
  '404 Error': 'Error 404',
  'Contact {name}, {restaurantTypeInCity}': 'Contacta a {name}, {restaurantTypeInCity}',
  'Site created with': 'Sitio creado con',
};

export default ES;

