const IT = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'Errore 404',
  Restaurant: 'Ristorante',
  Pages: 'Pagine',
  Contact: 'Contatto',
  in: 'a',
  Monday: 'Lunedì',
  Tuesday: 'Martedì',
  Wednesday: 'Mercoledì',
  Thursday: 'Giovedì',
  Friday: 'Venerdì',
  Saturday: 'Sabato',
  Sunday: 'Domenica',
  Closed: 'Chiuso',
  'Opening hours': 'Orari di apertura',
  'Order now': 'Ordina ora',
  Order: 'Ordina',
  Book: 'Prenota',
  Delivery: 'Consegna',
  Booking: 'Prenotazione',
  'Order in delivery': 'Ordina in consegna',
  'Order in Click & Collect': 'Ordina in Click & Collect',
  'Our services': 'I nostri servizi',
  'At {name}, we make online reservations easy: instant and without prior registration': 'Da {name}, rendiamo facili le prenotazioni online: istantanee e senza registrazione preventiva',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': 'Da {name}, preferiamo il Click & Collect: nessuna registrazione, pagamento online o presso il ristorante (carta di credito e buoni pasto)',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': 'Da {name}, consegniamo ovunque a {city}: stesso prezzo del ristorante e nessun costo di servizio',
  'Book a table': 'Prenota un tavolo',
  'Order and book online at {name}': 'Ordina e prenota online su {name}',
  'Language selection': 'Selezione lingua',
  'Theme selection': 'Selezione tema',
  'They talk about our restaurant {name} better than us': 'Parlano del nostro ristorante {name} meglio di noi',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': 'Da {name}, ci impegniamo a offrirti un\'esperienza culinaria autentica e memorabile! Ecco cosa hanno detto alcuni dei nostri clienti sulla loro visita al ristorante in {formattedShortAddress}:',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': 'Al ristorante {name}, offriamo una vasta gamma di servizi per rendere la tua esperienza culinaria ancora più comoda e piacevole! Scopri i nostri servizi di consegna, Click & Collect e prenotazione online per sfruttare al massimo il nostro {formattedRestaurantType}, a casa o nel nostro locale, ma sempre senza attese',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5 basato su {nbReviews} recensioni Google',
  'Read more reviews': 'Leggi altre recensioni',
  Itinary: 'Itinerario',
  'Order / Book': 'Ordina / Prenota',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': 'Scopri il nostro menu, disponibile sul posto nel ristorante, in Click & Collect e con consegna',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': 'Puoi ordinare in Click & Collect o con consegna direttamente dal nostro sito web, prova!',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': 'Benvenuti su {name}! Vieni a scoprire il nostro {formattedRestaurantType} situato in {formattedShortAddress}! Il nostro ristorante offre una cucina autentica: cuciniamo piatti fatti in casa con prodotti freschi! Per facilitare la tua visita, non esitare a prenotare online. Puoi anche consultare il nostro menu online e effettuare il tuo ordine ora: Click and Collect e consegna',
  Home: 'Home',
  Contact: 'Contatto',
  'Click & Collect': 'Click & Collect',
  Delivery: 'Consegna',
  Menu: 'Menu',
  Book: 'Prenota',
  'Book at {name}': 'Prenota su {name}',
  'Book a table at {name}': 'Prenota un tavolo su {name}',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': 'Da {name}, un {formattedRestaurantType} in {formattedShortAddress}, ti invitiamo a prenotare il tuo tavolo online Il nostro sistema di prenotazione è gratuito e non richiede registrazione. Prenota il tuo tavolo online su {restaurantName} e incontraci in {formattedShortAddress2} per scoprire il nostro ristorante e i nostri piatti autentici',
  'Page not found': 'Pagina non trovata',
  'Back to home page': 'Torna alla pagina principale',
  'Menu of {name}': 'Menu di {name}',
  'Discover the menu of {name}, {formattedRestaurantType}': 'Scopri il menu di {name}, {formattedRestaurantType}',
  '{name} Delivery': 'Consegna {name}',
  'delivered to your home or office': 'consegnato a casa o in ufficio',
  'to go!': 'da asporto!',
  '{name} food delivery': 'Consegna di cibo {name}',
  'Click & Collect {name}': 'Click & Collect {name}',
  'Have {name} delivered to you without service fees!': 'Fallo consegnare {name} senza spese di servizio!',
  Fast: 'Veloce',
  'No registration': 'Nessuna registrazione',
  Economic: 'Economico',
  'No service fees': 'Nessuna spesa di servizio',
  Convenient: 'Conveniente',
  'Skip the line': 'Salta la fila',
  '{name} in Click & Collect': '{name} in Click & Collect',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': 'Il nostro sistema Click & Collect non richiede registrazione e puoi pagare online o al ristorante, con carta di credito o buoni pasto',
  'Order online at {name} with Click & Collect to save time!': 'Ordina online su {name} con il servizio Click & Collect per risparmiare tempo!',
  Cheap: 'Economico',
  'Same price as restaurant': 'Stesso prezzo del ristorante',
  Anywhere: 'Ovunque',
  'Delivery in and around {city}': 'Consegna a {city} e dintorni',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': 'Fatti consegnare {name} al prezzo che pagheresti in un ristorante, grazie a Komdab',
  'Dishes at the same prices as à la carte and no service charges!': 'Piatti allo stesso prezzo della carta e senza spese di servizio!',
  of: 'di',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': 'Consulta il menu di {name} {formattedRestaurantType} in {formattedShortAddress}. Ordina da asporto con il servizio Click & Collect o con la consegna senza spese di servizio',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': 'Prenota un tavolo online su {name} {formattedRestaurantType} in {formattedShortAddress}. Prenota gratuitamente da {name2} senza registrazione',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': 'Fatti consegnare {name} {formattedRestaurantType}! Consegne senza spese di servizio, allo stesso prezzo della carta, ovunque a {city} e dintorni',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': 'Ordina con il servizio Click & Collect da {name} {formattedRestaurantType} Nessuna spesa di servizio e nessuna registrazione Paga online o al ristorante in {formattedShortAddress}',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}, {formattedRestaurantType}, {formattedShortAddress}. Prenota e ordina con il servizio Click & Collect o la consegna sul nostro sito.',
  Address: 'Indirizzo',
  'Contact {name}': 'Contatta {name}',
  '{name} is here to help!': '{name} è qui per aiutarti!',
  'First name': 'Nome',
  'Last name': 'Cognome',
  'Phone number': 'Numero di telefono',
  Email: 'Email',
  Message: 'Messaggio',
  Error: 'Errore',
  'First name is missing': 'Manca il nome',
  'Last name is missing': 'Manca il cognome',
  'Email is invalid': 'Email non valida',
  'Message is missing': 'Manca il messaggio',
  Send: 'Invia',
  '{name} restaurant': 'Ristorante {name}',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': 'Il tuo {formattedRestaurantType} {name} è pronto ad ascoltare tutte le tue richieste! Per informazioni, richieste specifiche, privatizzazioni o servizi di catering, non esitare a inviarci un messaggio e ti risponderemo al più presto!',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{formattedRestaurantTypeUpperFirst} a {city}',
  Sent: 'Inviato',
  '404 Error': 'Errore 404',
  'Contact {name}, {restaurantTypeInCity}': 'Contatta {name}, {restaurantTypeInCity}',
  'Site created with': 'Sito creato con',
};

export default IT;
