const JA = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'エラー404',
  Restaurant: 'レストラン',
  Pages: 'ページ',
  Contact: 'コンタクト',
  in: 'à',
  Monday: '月曜日',
  Tuesday: '火曜日',
  Wednesday: '水曜日',
  Thursday: '木曜日',
  Friday: '金曜日',
  Saturday: '土曜日',
  Sunday: '日曜日',
  Closed: '閉店',
  'Opening hours': '営業時間',
  'Order now': '今すぐ注文',
  Order: '注文',
  Book: '予約',
  Delivery: '配達',
  Booking: '予約',
  'Order in delivery': '配達で注文',
  'Order in Click & Collect': 'クリック＆コレクトで注文',
  'Our services': '私たちのサービス',
  'At {name}, we make online reservations easy: instant and without prior registration': '{name}では、オンライン予約を簡単に行います：即時で事前登録不要',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': '{name}では、Click & Collectをお勧めします：登録不要、オンラインまたはレストランでの支払い（クレジットカードと飲食店のクーポン）',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': '{name}では、{city}内のどこにでも配達します：レストランと同じ価格でサービス料はかかりません',
  'Book a table': 'テーブルを予約',
  'Order and book online at {name}': '{name}でオンラインで注文および予約',
  'Language selection': '言語選択',
  'Theme selection': 'テーマ選択',
  'They talk about our restaurant {name} better than us': '彼らは私たちのレストラン {name} について、私たちよりも良く話しています',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': '{name} では、本物の思い出に残る食事体験を提供することにコミットしています！ こちらは、一部のお客様が {formattedShortAddress} のレストランへの訪問について言ったことです：',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': '{name} レストランでは、食事体験をさらに便利で楽しいものにするための幅広いサービスを提供しています！ 当社の配達、クリック＆コレクト、オンライン予約サービスをご利用いただき、{formattedRestaurantType} を最大限にお楽しみください.自宅または当社の施設で、いつでも待たずに.',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5、{nbReviews} 件のGoogleレビューをもとに',
  'Read more reviews': '他のレビューを読む',
  Itinary: '経路',
  'Order / Book': '注文 / 予約',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': '当社のメニューをお楽しみください.レストラン内、クリック＆コレクト、および配達でご利用いただけます.',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': '当社のウェブサイトから直接クリック＆コレクトまたは配達で注文できます、ぜひお試しください！',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': '{name} へようこそ！ {formattedShortAddress} にある当社の {formattedRestaurantType} をお楽しみください！ 当レストランは本格的な料理を提供しています：新鮮な食材を使用した手作りの料理を調理しています！ ご来店をお手伝いするために、オンラインで予約することをお勧めします.オンラインでメニューをご覧いただき、今すぐ注文していただけます：クリック＆コレクトおよび配達',
  Home: 'ホーム',
  Contact: 'お問い合わせ',
  'Click & Collect': 'クリック＆コレクト',
  Delivery: '配達',
  Menu: 'メニュー',
  Book: '予約',
  'Book at {name}': '{name} で予約',
  'Book a table at {name}': '{name} でテーブルを予約',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': '{name} では、{formattedShortAddress} にある {formattedRestaurantType} を予約いただくことをお勧めします. 当社の予約システムは無料で、登録不要です.{restaurantName} でオンラインでテーブルを予約し、{formattedShortAddress2} で当社のレストランと本格的な料理をご覧いただけます.',
  'Page not found': 'ページが見つかりません',
  'Back to home page': 'ホームページに戻る',
  'Menu of {name}': '{name} のメニュー',
  'Discover the menu of {name}, {formattedRestaurantType}': '{name}、{formattedRestaurantType} のメニューをご覧ください',
  '{name} Delivery': '{name} の配達',
  'delivered to your home or office': '自宅やオフィスに配達されます',
  'to go!': 'テイクアウト！',
  '{name} food delivery': '{name} の料理の配達',
  'Click & Collect {name}': 'クリック＆コレクト {name}',
  'Have {name} delivered to you without service fees!': 'サービス料なしで {name} をお届けします！',
  Fast: '速い',
  'No registration': '登録不要',
  Economic: '経済的',
  'No service fees': 'サービス料なし',
  Convenient: '便利',
  'Skip the line': '行列をスキップ',
  '{name} in Click & Collect': 'クリック＆コレクトでの {name}',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': '当社のクリック＆コレクトシステムには登録が必要ありません.クレジットカードまたは食事券でオンラインまたはレストランで支払うことができます.',
  'Order online at {name} with Click & Collect to save time!': '{name} でオンラインで注文し、クリック＆コレクトで時間を節約しましょう！',
  Cheap: '安い',
  'Same price as restaurant': 'レストランと同じ価格',
  Anywhere: 'どこでも',
  'Delivery in and around {city}': '{city} およびその周辺への配達',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': 'Komdab のおかげで、レストランで支払うのと同じ価格で {name} をお届けします',
  'Dishes at the same prices as à la carte and no service charges!': 'アラカルトと同じ価格で料理を提供し、サービス料はありません！',
  of: 'の',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': '{formattedShortAddress} で {name} {formattedRestaurantType} のメニューをご覧いただき、クリック＆コレクトまたは配達でテイクアウトを注文し、サービス料なしで',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': '{formattedShortAddress} でオンラインでテーブルを予約し、登録せずに無料で {name2} で予約',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': '{name} {formattedRestaurantType} をお届けします！ サービス料はかかりません、アラカルトと同じ価格で、{city} およびその周辺地域全域で',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': '{name} {formattedRestaurantType} でクリック＆コレクトで注文 サービス料はかかりません、登録不要 オンラインまたは {formattedShortAddress} のレストランで支払い',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}、{formattedRestaurantType}、{formattedShortAddress}.ウェブサイトでクリック＆コレクトまたは配達で予約と注文をしてください',
  Address: '住所',
  'Contact {name}': '{name} に連絡',
  '{name} is here to help!': '{name} がお手伝いします！',
  'First name': '名',
  'Last name': '姓',
  'Phone number': '電話番号',
  Email: 'メールアドレス',
  Message: 'メッセージ',
  Error: 'エラー',
  'First name is missing': '名がありません',
  'Last name is missing': '姓がありません',
  'Email is invalid': 'メールアドレスが無効です',
  'Message is missing': 'メッセージがありません',
  Send: '送信',
  '{name} restaurant': '{name} レストラン',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': 'あなたの {formattedRestaurantType} {name} はすべてのリクエストに耳を傾ける準備ができています！ 情報、特別なリクエスト、プライバシー保護、またはケータリングサービスについての質問がある場合は、お気軽にメッセージをお送りください.できるだけ早くご連絡いたします！',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{city} の {formattedRestaurantTypeUpperFirst}',
  Sent: '送信済み',
  '404 Error': '404 エラー',
  'Contact {name}, {restaurantTypeInCity}': '{name}、{restaurantTypeInCity} に連絡',
  'Site created with': 'で作成したサイト',
};

export default JA;
