const NL = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'Fout 404',
  Restaurant: 'Restaurant',
  Pages: 'Pagina\'s',
  Contact: 'Contact',
  in: 'in',
  Monday: 'Maandag',
  Tuesday: 'Dinsdag',
  Wednesday: 'Woensdag',
  Thursday: 'Donderdag',
  Friday: 'Vrijdag',
  Saturday: 'Zaterdag',
  Sunday: 'Zondag',
  Closed: 'Gesloten',
  'Opening hours': 'Openingstijden',
  'Order now': 'Nu bestellen',
  Order: 'Bestellen',
  Book: 'Reserveren',
  Delivery: 'Bezorging',
  Booking: 'Reservering',
  'Order in delivery': 'Bestel voor bezorging',
  'Order in Click & Collect': 'Bestel met Click & Collect',
  'Our services': 'Onze diensten',
  'At {name}, we make online reservations easy: instant and without prior registration': 'Bij {name} maken we online reserveren eenvoudig: direct en zonder voorafgaande registratie',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': 'Bij {name} geven we de voorkeur aan Click & Collect: geen registratie, betaling online of in het restaurant (creditcard en restaurantbonnen)',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': 'Bij {name} bezorgen we overal in {city}: dezelfde prijs als in het restaurant en geen servicekosten',
  'Book a table': 'Reserveer een tafel',
  'Order and book online at {name}': 'Bestel en reserveer online bij {name}',
  'Language selection': 'Taalkeuze',
  'Theme selection': 'Themakeuze',
  'They talk about our restaurant {name} better than us': 'Ze praten beter over ons restaurant {name} dan wij',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': 'Bij {name} zijn we toegewijd om u een authentieke en gedenkwaardige eetervaring te bieden! Hier is wat sommige van onze klanten te zeggen hadden over hun bezoek aan het restaurant op {formattedShortAddress}:',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': 'In het restaurant {name} bieden we een volledig scala aan diensten om uw eetervaring nog handiger en plezieriger te maken! Ontdek onze bezorg-, Click & Collect- en online reserveringsdiensten om optimaal te genieten van ons {formattedRestaurantType}, thuis of in ons etablissement, maar altijd zonder te wachten',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5 op basis van {nbReviews} Google-recensies',
  'Read more reviews': 'Lees meer recensies',
  Itinary: 'Routebeschrijving',
  'Order / Book': 'Bestellen / Reserveren',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': 'Ontdek ons menu, beschikbaar ter plaatse in het restaurant, bij Click & Collect en bij bezorging.',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': 'U kunt direct vanaf onze website bestellen bij Click & Collect of bezorging, probeer het eens!',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': 'Welkom bij {name}! Kom ons {formattedRestaurantType} ontdekken gelegen aan {formattedShortAddress}! Ons restaurant biedt authentieke gerechten: we koken huisgemaakte gerechten gemaakt van verse producten! Om uw bezoek te vergemakkelijken, aarzel niet om online te reserveren. U kunt ook ons menu online raadplegen en nu bestellen: Click and Collect en bezorging',
  Home: 'Thuis',
  Contact: 'Contact',
  'Click & Collect': 'Click & Collect',
  Delivery: 'Bezorging',
  Menu: 'Menu',
  Book: 'Reserveren',
  'Book at {name}': 'Reserveer bij {name}',
  'Book a table at {name}': 'Reserveer een tafel bij {name}',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': 'Bij {name}, een {formattedRestaurantType} bij {formattedShortAddress}, nodigen we u uit om uw tafel online te reserveren. Ons reserveringssysteem is gratis en vereist geen registratie. Reserveer uw tafel online bij {restaurantName} en ontmoet ons bij {formattedShortAddress2} om ons restaurant en onze authentieke gerechten te ontdekken',
  'Page not found': 'Pagina niet gevonden',
  'Back to home page': 'Terug naar de startpagina',
  'Menu of {name}': 'Menu van {name}',
  'Discover the menu of {name}, {formattedRestaurantType}': 'Ontdek het menu van {name}, {formattedRestaurantType}',
  '{name} Delivery': '{name} Bezorging',
  'delivered to your home or office': 'geleverd aan uw huis of kantoor',
  'to go!': 'om mee te nemen!',
  '{name} food delivery': '{name} voedselbezorging',
  'Click & Collect {name}': 'Click & Collect {name}',
  'Have {name} delivered to you without service fees!': 'Laat {name} bij u bezorgen zonder servicekosten!',
  Fast: 'Snel',
  'No registration': 'Geen registratie',
  Economic: 'Economisch',
  'No service fees': 'Geen servicekosten',
  Convenient: 'Handig',
  'Skip the line': 'Sla de rij over',
  '{name} in Click & Collect': '{name} bij Click & Collect',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': 'Ons Click & Collect-systeem vereist geen registratie en u kunt online of in het restaurant betalen, met creditcard of maaltijdcheques',
  'Order online at {name} with Click & Collect to save time!': 'Bestel online bij {name} met Click & Collect om tijd te besparen!',
  Cheap: 'Goedkoop',
  'Same price as restaurant': 'Zelfde prijs als in het restaurant',
  Anywhere: 'Overal',
  'Delivery in and around {city}': 'Bezorging in en rond {city}',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': 'Laat {name} bij u bezorgen voor dezelfde prijs als in een restaurant, dankzij Komdab',
  'Dishes at the same prices as à la carte and no service charges!': 'Gerechten tegen dezelfde prijzen als à la carte en zonder servicekosten!',
  of: 'van',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': 'Bekijk het menu van {name} {formattedRestaurantType} bij {formattedShortAddress} Bestel afhaalmaaltijden met Click & Collect of bezorging zonder servicekosten',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': 'Reserveer online een tafel bij {name} {formattedRestaurantType} bij {formattedShortAddress} Reserveer gratis bij {name2} zonder registratie',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': 'Laat {name} {formattedRestaurantType} bij u bezorgen! Bezorging zonder servicekosten, tegen dezelfde prijs als à la carte, overal in {city} en de omliggende gebieden',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': 'Bestel in Click & Collect bij {name} {formattedRestaurantType} Geen servicekosten en geen registratie Betaal online of in het restaurant bij {formattedShortAddress}',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}, {formattedRestaurantType}, {formattedShortAddress}. Boek en bestel via Click & Collect of levering op onze website.',
  Address: 'Adres',
  'Contact {name}': 'Contacteer {name}',
  '{name} is here to help!': '{name} staat voor u klaar!',
  'First name': 'Voornaam',
  'Last name': 'Achternaam',
  'Phone number': 'Telefoonnummer',
  Email: 'E-mail',
  Message: 'Bericht',
  Error: 'Fout',
  'First name is missing': 'Voornaam ontbreekt',
  'Last name is missing': 'Achternaam ontbreekt',
  'Email is invalid': 'Ongeldige e-mail',
  'Message is missing': 'Bericht ontbreekt',
  Send: 'Verzenden',
  '{name} restaurant': '{name} restaurant',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': 'Uw {formattedRestaurantType} {name} staat klaar om naar al uw verzoeken te luisteren! Voor informatie, specifieke verzoeken, privatisering of cateringdiensten, aarzel niet om ons een bericht te sturen en we zullen zo snel mogelijk bij u terugkomen!',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{formattedRestaurantTypeUpperFirst} in {city}',
  Sent: 'Verzonden',
  '404 Error': '404 Fout',
  'Contact {name}, {restaurantTypeInCity}': 'Contacteer {name}, {restaurantTypeInCity}',
  'Site created with': 'Site gemaakt met',
};

export default NL;