const PT = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'Erro 404',
  Restaurant: 'Restaurante',
  Pages: 'Páginas',
  Contact: 'Contato',
  in: 'em',
  Monday: 'Segunda-feira',
  Tuesday: 'Terça-feira',
  Wednesday: 'Quarta-feira',
  Thursday: 'Quinta-feira',
  Friday: 'Sexta-feira',
  Saturday: 'Sábado',
  Sunday: 'Domingo',
  Closed: 'Fechado',
  'Opening hours': 'Horário de funcionamento',
  'Order now': 'Encomendar agora',
  Order: 'Encomendar',
  Book: 'Reservar',
  Delivery: 'Entrega',
  Booking: 'Reserva',
  'Order in delivery': 'Encomendar na entrega',
  'Order in Click & Collect': 'Encomendar no Click & Collect',
  'Our services': 'Nossos serviços',
  'At {name}, we make online reservations easy: instant and without prior registration': 'No {name}, tornamos as reservas online fáceis: instantâneas e sem registro prévio',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': 'No {name}, preferimos o Click & Collect: sem registro, pagamento online ou no restaurante (cartão de crédito e vales-refeição)',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': 'No {name}, entregamos em qualquer lugar em {city}: mesmo preço do restaurante e sem taxa de serviço',
  'Book a table': 'Reservar uma mesa',
  'Order and book online at {name}': 'Encomendar e reservar online em {name}',
  'Language selection': 'Seleção de idioma',
  'Theme selection': 'Seleção de tema',
  'They talk about our restaurant {name} better than us': 'Eles falam sobre nosso restaurante {name} melhor do que nós',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': 'No {name}, estamos empenhados em proporcionar-lhe uma experiência gastronômica autêntica e memorável! Veja o que alguns de nossos clientes disseram sobre sua visita ao restaurante em {formattedShortAddress}:',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': 'No restaurante {name}, oferecemos uma gama completa de serviços para tornar sua experiência gastronômica ainda mais conveniente e agradável! Descubra nossos serviços de entrega, Click & Collect e reserva online para aproveitar ao máximo o nosso {formattedRestaurantType}, em casa ou em nosso estabelecimento, mas sempre sem esperar',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5 com base em {nbReviews} avaliações no Google',
  'Read more reviews': 'Leia mais avaliações',
  Itinary: 'Itinerário',
  'Order / Book': 'Encomendar / Reservar',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': 'Descubra nosso cardápio, disponível no restaurante, no Click & Collect e na entrega',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': 'Você pode encomendar no Click & Collect ou na entrega diretamente em nosso site, experimente!',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': 'Bem-vindo ao {name}! Venha descobrir nosso {formattedRestaurantType} localizado em {formattedShortAddress}! Nosso restaurante oferece culinária autêntica: cozinhamos pratos caseiros feitos com produtos frescos! Para facilitar sua visita, não hesite em reservar online. Você também pode consultar nosso cardápio online e fazer seu pedido agora: Click and Collect e entrega',
  Home: 'Início',
  Contact: 'Contato',
  'Click & Collect': 'Click & Collect',
  Delivery: 'Entrega',
  Menu: 'Cardápio',
  Book: 'Reservar',
  'Book at {name}': 'Reservar em {name}',
  'Book a table at {name}': 'Reservar uma mesa em {name}',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': 'No {name}, um {formattedRestaurantType} em {formattedShortAddress}, convidamos você a reservar sua mesa online. Nosso sistema de reserva é gratuito e não requer registro. Reserve sua mesa online em {restaurantName} e nos encontre em {formattedShortAddress2} para descobrir nosso restaurante e nossos pratos autênticos',
  'Page not found': 'Página não encontrada',
  'Back to home page': 'Voltar para a página inicial',
  'Menu of {name}': 'Cardápio de {name}',
  'Discover the menu of {name}, {formattedRestaurantType}': 'Descubra o cardápio de {name}, {formattedRestaurantType}',
  '{name} Delivery': 'Entrega {name}',
  'delivered to your home or office': 'entregue em sua casa ou escritório',
  'to go!': 'para viagem!',
  '{name} food delivery': 'Entrega de comida {name}',
  'Click & Collect {name}': 'Click & Collect {name}',
  'Have {name} delivered to you without service fees!': 'Receba {name} entregue em sua casa sem taxas de serviço!',
  Fast: 'Rápido',
  'No registration': 'Sem registro',
  Economic: 'Econômico',
  'No service fees': 'Sem taxas de serviço',
  Convenient: 'Conveniente',
  'Skip the line': 'Pule a fila',
  '{name} in Click & Collect': '{name} no Click & Collect',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': 'Nosso sistema de Click & Collect não requer registro e você pode pagar online ou no restaurante, com cartão de crédito ou vales-refeição',
  'Order online at {name} with Click & Collect to save time!': 'Encomende online em {name} com o Click & Collect para economizar tempo!',
  Cheap: 'Barato',
  'Same price as restaurant': 'Mesmo preço do restaurante',
  Anywhere: 'Em qualquer lugar',
  'Delivery in and around {city}': 'Entrega em {city} e região',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': 'Tenha {name} entregue em sua casa pelo mesmo preço que você pagaria em um restaurante, graças ao Komdab',
  'Dishes at the same prices as à la carte and no service charges!': 'Pratos pelo mesmo preço do cardápio e sem taxas de serviço!',
  of: 'de',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': 'Consulte o cardápio de {name} {formattedRestaurantType} em {formattedShortAddress}. Faça um pedido para viagem usando o Click & Collect ou entrega sem taxas de serviço',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': 'Reserve uma mesa online no {name} {formattedRestaurantType} em {formattedShortAddress}. Reserve gratuitamente no {name2} sem registro',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': 'Receba {name} {formattedRestaurantType} em sua casa! Entregas sem taxas de serviço, pelo mesmo preço do cardápio, em toda {city} e região',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': 'Faça seu pedido no Click & Collect no {name} {formattedRestaurantType}. Sem taxas de serviço e sem registro. Pague online ou no restaurante em {formattedShortAddress}',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}, {formattedRestaurantType}, {formattedShortAddress}. Reserve e faça o pedido em Click & Collect ou entrega no nosso site.',
  Address: 'Endereço',
  'Contact {name}': 'Contate {name}',
  '{name} is here to help!': '{name} está aqui para ajudar!',
  'First name': 'Primeiro nome',
  'Last name': 'Sobrenome',
  'Phone number': 'Número de telefone',
  Email: 'Email',
  Message: 'Mensagem',
  Error: 'Erro',
  'First name is missing': 'Primeiro nome está faltando',
  'Last name is missing': 'Sobrenome está faltando',
  'Email is invalid': 'Email é inválido',
  'Message is missing': 'Mensagem está faltando',
  Send: 'Enviar',
  '{name} restaurant': 'Restaurante {name}',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': 'Seu {formattedRestaurantType} {name} está pronto para ouvir todas as suas solicitações! Para informações, solicitações específicas, privatização ou serviços de catering, não hesite em nos enviar uma mensagem e entraremos em contato o mais rápido possível!',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{formattedRestaurantTypeUpperFirst} em {city}',
  Sent: 'Enviado',
  '404 Error': 'Erro 404',
  'Contact {name}, {restaurantTypeInCity}': 'Contate {name}, {restaurantTypeInCity}',
  'Site created with': 'Site criado com',
};

export default PT;
