const ZH = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': '错误 404',
  Restaurant: '餐厅',
  Pages: '页面',
  Contact: '联系',
  in: '在',
  Monday: '星期一',
  Tuesday: '星期二',
  Wednesday: '星期三',
  Thursday: '星期四',
  Friday: '星期五',
  Saturday: '星期六',
  Sunday: '星期日',
  Closed: '关闭',
  'Opening hours': '营业时间',
  'Order now': '立即下单',
  Order: '下单',
  Book: '预订',
  Delivery: '送货',
  Booking: '预约',
  'Order in delivery': '送货下单',
  'Order in Click & Collect': '点击并收集下单',
  'Our services': '我们的服务',
  'At {name}, we make online reservations easy: instant and without prior registration': '在{name}, 我们简化了在线预订：即时且无需提前注册',
  'At {name}, we prefer Click & Collect: no registration, payment online or at the restaurant (credit card and restaurant vouchers)': '在{name}, 我们更喜欢点击并收集：无需注册, 在线或在餐厅付款（信用卡和餐厅优惠券）',
  'At {name}, we deliver anywhere in {city}: same price as at the restaurant and no service charge': '在{name}, 我们随时为您在{city}的任何地方提供送餐服务：与餐厅价格相同, 无需服务费',
  'Book a table': '预订餐桌',
  'Order and book online at {name}': '在{name}在线订购和预订',
  'Language selection': '语言选择',
  'Theme selection': '主题选择',
  'They talk about our restaurant {name} better than us': '他们比我们更好地谈论了我们的餐厅{name}',
  'At {name}, we\'re committed to providing you with an authentic and memorable dining experience! Here\'s what some of our customers had to say about their visit to the restaurant at {formattedShortAddress}:': '在{name}, 我们致力于为您提供真实而难忘的用餐体验！以下是一些客户对他们在位于{formattedShortAddress}的餐厅参观的看法：',
  'At the restaurant {name}, we offer a full range of services to make your food experience even more convenient and enjoyable! Discover our delivery, Click & Collect and online reservation services to make the most of our {formattedRestaurantType}, at home or at our establishment, but always without waiting': '在餐厅{name}, 我们提供一整套服务, 使您的用餐体验更加方便和愉快！发现我们的送餐、点击并收集以及在线预订服务, 以充分利用我们的{formattedRestaurantType}, 无论是在家里还是在我们的场所, 但始终无需等待',
  '{googleRating} / 5 based on {nbReviews} Google reviews': '{googleRating} / 5基于{nbReviews}条Google评论',
  'Read more reviews': '阅读更多评论',
  Itinary: '行程',
  'Order / Book': '下单/预订',
  'Discover our menu, available on-site at the restaurant, in Click & Collect and in delivery': '发现我们的菜单, 在餐厅现场、点击并收集和送餐服务中都可用',
  'You can order in Click & Collect or in delivery directly from our website, give it a try!': '您可以直接从我们的网站订购点击并收集或送餐服务, 试一试！',
  'Welcome to {name}! Come discover our {formattedRestaurantType} located at {formattedShortAddress}! Our restaurant offers authentic cuisine: we cook homemade dishes made from fresh products! In order to facilitate your visit, do not hesitate to book online You can also consult our menu online and place your order now: Click and Collect and delivery': '欢迎来到{name}！来发现我们位于{formattedShortAddress}的{formattedRestaurantType}！我们的餐厅提供地道的美食：我们烹饪新鲜产品制成的家常菜肴！为了方便您的访问, 不要犹豫在线预订。您还可以在线查看我们的菜单, 并立即下订单：点击并收集和送货',
  Home: '主页',
  Contact: '联系',
  'Click & Collect': '点击并收集',
  Delivery: '送货',
  Menu: '菜单',
  Book: '预订',
  'Book at {name}': '在{name}预订',
  'Book a table at {name}': '在{name}预订餐桌',
  'At {name}, a {formattedRestaurantType} at {formattedShortAddress}, we invite you to book your table online Our reservation system is free and requires no registration Book your table online at {restaurantName} and meet us at {formattedShortAddress2} to discover our restaurant and our authentic dishes': '在餐厅{name}, 位于{formattedShortAddress}的{formattedRestaurantType}, 我们邀请您在线预订餐桌。我们的预订系统是免费的, 无需注册。在{restaurantName}的网上预订餐桌, 并在{formattedShortAddress2}与我们见面, 发现我们的餐厅和地道的美食',
  'Page not found': '页面未找到',
  'Back to home page': '返回主页',
  'Menu of {name}': '{name}的菜单',
  'Discover the menu of {name}, {formattedRestaurantType}': '发现{name}, {formattedRestaurantType}的菜单',
  '{name} Delivery': '{name}送货',
  'delivered to your home or office': '送货到您的家或办公室',
  'to go!': '带走！',
  '{name} food delivery': '{name}食品送货',
  'Click & Collect {name}': '点击并收集{name}',
  'Have {name} delivered to you without service fees!': '将{name}送到您手上, 无需支付服务费！',
  Fast: '快速',
  'No registration': '无需注册',
  Economic: '经济',
  'No service fees': '无服务费',
  Convenient: '方便',
  'Skip the line': '跳过排队',
  '{name} in Click & Collect': '{name} 在Click & Collect中',
  'Our Click & Collect system requires no registration and you can pay online or at the restaurant, by credit card or meal vouchers': '我们的Click & Collect系统无需注册, 您可以在线支付或在餐厅支付, 可以使用信用卡或餐券',
  'Order online at {name} with Click & Collect to save time!': '在{name}在线订购, 使用Click & Collect节省时间！',
  Cheap: '便宜',
  'Same price as restaurant': '与餐厅价格相同',
  Anywhere: '任何地方',
  'Delivery in and around {city}': '在{city}及周边地区送货',
  'Have {name} delivered to you for the same price as you would pay in a restaurant, thanks to Komdab': '通过Komdab, 以与餐厅相同的价格将{name}送到您那里',
  'Dishes at the same prices as à la carte and no service charges!': '与à la carte相同价格的菜肴, 无需服务费！',
  of: '的',
  'Consult the menu of {name} {formattedRestaurantType} at {formattedShortAddress} Order takeaway using Click & Collect or in delivery without service fees': '在{formattedShortAddress}咨询{name} {formattedRestaurantType}的菜单, 使用Click & Collect或送货订购外卖, 无需支付服务费',
  'Book a table online at {name} {formattedRestaurantType} at {formattedShortAddress} Reserve for free at {name2} without registration': '在线在{formattedShortAddress}的{name} {formattedRestaurantType}预订餐桌, 在{name2}免费预订, 无需注册',
  'Have {name} {formattedRestaurantType} delivered to you! Deliveries without service fees, at the same price as à la carte, everywhere in {city} and its surrounding areas': '将{name} {formattedRestaurantType}送到您！无需支付服务费, 价格与à la carte相同, 覆盖{city}及其周边地区的所有地方',
  'Order in Click & Collect at {name} {formattedRestaurantType} No service fees and no registration Pay online or at the restaurant at {formattedShortAddress}': '在{formattedShortAddress}的{name} {formattedRestaurantType}中使用Click & Collect下订单, 无需支付服务费, 无需注册, 在线支付或在餐厅支付',
  '{name}, {formattedRestaurantType}, {formattedShortAddress} Book and order in Click & Collect or delivery on our site': '{name}, {formattedRestaurantType}, {formattedShortAddress}. 在我们的网站上预订并下单, 选择取餐或送货服务.',
  Address: '地址',
  'Contact {name}': '联系{name}',
  '{name} is here to help!': '{name}在这里帮助您！',
  'First name': '名字',
  'Last name': '姓',
  'Phone number': '电话号码',
  Email: '电子邮件',
  Message: '消息',
  Error: '错误',
  'First name is missing': '名字缺失',
  'Last name is missing': '姓缺失',
  'Email is invalid': '电子邮件无效',
  'Message is missing': '消息缺失',
  Send: '发送',
  '{name} restaurant': '{name}餐厅',
  'Your {formattedRestaurantType} {name} is ready to listen to all your requests! For information, specific requests, privatization or catering services, don\'t hesitate to send us a message and we\'ll get back to you as soon as possible!': '您的{formattedRestaurantType} {name}已准备好倾听您的所有请求！有关信息、特定请求、私人化或餐饮服务, 请随时给我们发送消息, 我们将尽快回复您！',
  '{formattedRestaurantTypeUpperFirst} in {city}': '{city}中的{formattedRestaurantTypeUpperFirst}',
  Sent: '已发送',
  '404 Error': '404错误',
  'Contact {name}, {restaurantTypeInCity}': '联系{name}, {restaurantTypeInCity}',
  'Site created with': '使用创建的网站',
};

export default ZH;
