const EN = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'The original website had numerous errors and questionable practices, making it a perfect example of a situation that needed correction*p* I undertook significant work to address these issues, with the goal of not only achieving an excellent audit tool rating but also discovering best practices for improving SEO and user experience*p*': 'The original website had numerous errors and questionable practices, making it a perfect example of a situation that needed correction. I undertook significant work to address these issues, with the goal of not only achieving an excellent audit tool rating but also discovering best practices for improving SEO and user experience.',
  'Everything was in disarray, and untangling it all was challenging*p* I meticulously examined HTML, CSS, jQuery, Bootstrap, and other aspects, removing, recoding, or reorganizing each element*p*': 'Everything was in disarray, and untangling it all was challenging. I meticulously examined HTML, CSS, jQuery, Bootstrap, and other aspects, removing, recoding, or reorganizing each element.',
  'This work, although tedious, was highly rewarding as it allowed me to become aware of the most common mistakes and learn how to code a site optimally from scratch*p* With this experience, it\'s now easier for me to plan ahead, even before writing the first line of code, knowing what to do and what not to do*p*': 'This work, although tedious, was highly rewarding as it allowed me to become aware of the most common mistakes and learn how to code a site optimally from scratch. With this experience, it\'s now easier for me to plan ahead, even before writing the first line of code, knowing what to do and what not to do.',
  'The project involved the development of a travel agency website with the goal of coding the website using HTML and CSS*p*': 'The project involved the development of a travel agency website with the goal of coding the website using HTML and CSS.',
  'During the course of the project, various skills were acquired, including versioning a project with Git and GitHub, implementing a responsive interface with HTML and CSS, integrating graphical content based on a layout with HTML and CSS, and setting up a front-end development environment*p*': 'During the course of the project, various skills were acquired, including versioning a project with Git and GitHub, implementing a responsive interface with HTML and CSS, integrating graphical content based on a layout with HTML and CSS, and setting up a front-end development environment.',
  'Positioning elements is a difficult task at first glance*p* I had trouble aligning sections consistently, especially in a responsive view*p* Fortunately, by immersing myself in Flexbox and CSS Grid, I was able to overcome these difficulties, creating complex layouts with greater ease*p*': 'Positioning elements is a difficult task at first glance. I had trouble aligning sections consistently, especially in a responsive view. Fortunately, by immersing myself in Flexbox and CSS Grid, I was able to overcome these difficulties, creating complex layouts with greater ease.',
  'Another obstacle was inconsistent rendering on different browsers*p* Initially, my design looked perfect on Chrome, but fell apart on Firefox or Safari*p* Using vendor prefixes and rigorous testing across multiple browsers helped me resolve these compatibility issues*p*': 'Another obstacle was inconsistent rendering on different browsers. Initially, my design looked perfect on Chrome, but fell apart on Firefox or Safari. Using vendor prefixes and rigorous testing across multiple browsers helped me resolve these compatibility issues.',
  'Finally, I had to refine my CSS selectors to avoid unexpected conflicts due to inheritance and cascading*p* By deepening my knowledge of CSS specificity, I was able to create a consistent and predictable style throughout the site*p*': 'Finally, I had to refine my CSS selectors to avoid unexpected conflicts due to inheritance and cascading. By deepening my knowledge of CSS specificity, I was able to create a consistent and predictable style throughout the site.',
};

export default EN;
