const FR = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  nl: 'Nederlands',
  pt: 'Português',
  it: 'Italiano',
  es: 'Español',
  zh: '中文',
  ja: '日本語',
  'Error 404': 'Erreur 404',
  'Page not found': 'Page introuvable',
  'Back to home page': 'Retour à la page d\'accueil',
  'First name': 'Prénom',
  'Last name': 'Nom',
  Email: 'Email',
  'Phone number': 'Numéro de téléphone',
  Message: 'Message',
  'First name is missing': 'Prénom manquant',
  'Last name is missing': 'Nom manquant',
  'Email is invalid': 'Email invalide',
  'Message is missing': 'Message manquant',
  Send: 'Envoyer',
  'I will be delighted to help you develop your web project': 'Je serai ravis de vous accompagner dans le développement de votre projet web',
  'Request a web development service provision': 'Demander une prestation de service de développement Web',
  'Full-stack web developer in Paris': 'Développeur web full-stack à Paris',
  'As a full-stack web developer, I can help you with the web development of your projects': 'Développeur web full-stack, je vous accompagne de le développement web de vos projets',
  'I need a web developer': 'J\'ai besoin d\'un développeur web',
  'Certified web developer': 'Développeur web certifié',
  'Certified “Web Developer“ by Open Classrooms, web applications I develop respects coding best practices': 'Certifié "Développeur Web" par OpenClassrooms, les applications web que je développe respectent les meilleurs pratiques de développement',
  'Web applications optimized SEO': 'Applications web optimisées SEO',
  'Web applications secured': 'Applications web sécurisées',
  'With a know-how in SEO for web applications, I ensure a strong visibility to your web applications': 'Avec un savoir-faire en SEO pour les applications web, j\'assure une forte visibilité à vos applications web',
  'Certified “Offensive Security Certified Pentester“ by OffSec, apps I develop respect OWASP secure development best practices': 'Certifié "Offensive Security Certified Pentester" par OffSec, les applications web que je développe respectent les pratiques de développement sécurisé de l\'OWASP',
  'Web development technologies I master': 'Les technologies de développement web que je maîtrise',
  'are necessarily adapted to your JS web applications and JS sites development needs': 'sont forcément adaptées aux besoins en développement de vos applications JS et sites web JS',
  'As a full-stack web developer, I love coding cutting-edge web applications': 'En tant que développeur web full-stack, j\'adore développer des applications web de pointe',
  'Learn more': 'En savoir plus',
  'The original website had numerous errors and questionable practices, making it a perfect example of a situation that needed correction*p* I undertook significant work to address these issues, with the goal of not only achieving an excellent audit tool rating but also discovering best practices for improving SEO and user experience*p*': 'Le site original comportait pratiquement toutes les erreurs et mauvaises pratiques possibles ce qui en fait le parfait cas d\'école. Un gros travail de nettoyage s\'imposait et j\'avais à cœur de tout mettre à plat pour non seulement obtenir une note quasi parfaite sur les outils d\'audit mais également pour découvrir toutes les bonnes pratiques qui permettent d\'obtenir le meilleur référencement possible et la meilleure expérience utilisateur.',
  'Everything was in disarray, and untangling it all was challenging*p* I meticulously examined HTML, CSS, jQuery, Bootstrap, and other aspects, removing, recoding, or reorganizing each element*p*': 'Absolument tout était sans dessus dessous et il fût difficile de tout démêler. HTML, CSS, jQuery, Bootstrap, css, etc. tout a été passé en revue pour être soit supprimé et recodé, soit remis en ordre.',
  'This work, although tedious, was highly rewarding as it allowed me to become aware of the most common mistakes and learn how to code a site optimally from scratch*p* With this experience, it\'s now easier for me to plan ahead, even before writing the first line of code, knowing what to do and what not to do*p*': 'Ce travail fastidieux mais néanmoins passionnant a été très enrichissant car il m\'a permis d\'ouvrir les yeux sur les erreurs les plus courantes afin de savoir comment bien coder un site de A à Z. Avec ce bagage, il m\'est plus aisé d\'envisager en amont, avant même la première ligne de code, ce que je dois ou ne dois surtout pas faire.',
  Mission: 'Mission',
  'Skills acquired': 'Compétences acquises',
  Details: 'Détails',
  'Debug and optimize Nina Carducci\'s freelance photographer portfolio': 'Déboguer et optimiser le portfolio de Nina Carducci, photographe freelance',
  'Optimize website performance': 'Optimiser les performances d\'un site web',
  'Debug a website using Chrome Dev-Tools': 'Débuguer un site web grâce aux Chrome Dev-Tools',
  'Write a test script to test a website': 'Rédiger un cahier de recette pour tester un site',
  'Optimization of Nina Carducci\'s website': 'Optimisation du site web de Nina Carducci',
  'Photographer portfolio': 'Portfolio d\'une photographe',
  'See on Github': 'Voir sur Github',
  'Developped by François': 'Développé par François',
  Home: 'Accueil',
  Contact: 'Contact',
  'Development of a travel agency website': 'Développement du site web d\'une agence de voyage',
  'Travel agency website': 'Site web d\'une agence de voyage',
  'Code the website of a traval agency using HTML and CSS': 'Coder le site web d\'une agence de voyage avec HTML et CSS',
  'Version a project with Git and Github': 'Versionner son projet avec Git et Github',
  'Implementing a responsive interface with HTML and CSS': 'Implémenter une interface responsive avec HTML et CSS',
  'Integrate graphical content according to a layout with HTML and CSS': 'Intégrer du contenu graphique conformément à une maquette avec HTML et CSS',
  'Setting up a front-end development environment': 'Installer un environnement de développement front-end',
  'The project involved the development of a travel agency website with the goal of coding the website using HTML and CSS*p*': 'Le projet consistait à développer le site web d\'une agence de voyage dans le but de coder le site web en utilisant HTML et CSS.',
  'During the course of the project, various skills were acquired, including versioning a project with Git and GitHub, implementing a responsive interface with HTML and CSS, integrating graphical content based on a layout with HTML and CSS, and setting up a front-end development environment*p*': 'Au cours du projet, diverses compétences ont été acquises, y compris le versionnement d\'un projet avec Git et GitHub, la mise en œuvre d\'une interface réactive avec HTML et CSS, l\'intégration d\'un contenu graphique basé sur une mise en page avec HTML et CSS, et la mise en place d\'un environnement de développement front-end.',
  'Below are some web applications I developped': 'Ci-dessous des applications que j\'ai développé',
  'Hire me': 'M\'engager',
  'Have a project ?': 'Vous avez un projet ?',
  'Language selection': 'Choix de la langue',
  'Theme selection': 'Choix du thème',
  'Let\'s discuss your project!': 'Discutons de votre projet !',
  Background: 'Formations',
  'From general engineer to web developer': 'D\'ingénieur général à développeur web',
  '2010 - 2016 | Engineer degree': '2010 - 2016 | Diplôme d\'ingénieur',
  '2016 | Business engineer degree': '2016 | Diplôme d\'ingénieur-manager',
  '2016 - 2023 | Cybersecurity consultant': '2016 - 2023 | Consultant en cybersécurité',
  '2023 | Web development': '2023 | Développement Web',
  Difficulties: 'Difficultés',
  'Positioning elements is a difficult task at first glance*p* I had trouble aligning sections consistently, especially in a responsive view*p* Fortunately, by immersing myself in Flexbox and CSS Grid, I was able to overcome these difficulties, creating complex layouts with greater ease*p*': 'Le positionnement des éléments est une tâche difficile au premier abord. J\'avais du mal à aligner les sections de manière cohérente, surtout en vue responsive. Heureusement, en me plongeant dans Flexbox et CSS Grid, j\'ai pu surmonter ces difficultés, réalisant des mises en page complexes avec une plus grande facilité.',
  'Another obstacle was inconsistent rendering on different browsers*p* Initially, my design looked perfect on Chrome, but fell apart on Firefox or Safari*p* Using vendor prefixes and rigorous testing across multiple browsers helped me resolve these compatibility issues*p*': 'Un autre obstacle était l\'incohérence du rendu sur différents navigateurs. Initialement, mon design semblait parfait sur Chrome, mais se désagrégeait sur Firefox ou Safari. L\'utilisation de préfixes de fournisseur et de tests rigoureux sur plusieurs navigateurs m\'a aidé à résoudre ces problèmes de compatibilité.',
  'Finally, I had to refine my CSS selectors to avoid unexpected conflicts due to inheritance and cascading*p* By deepening my knowledge of CSS specificity, I was able to create a consistent and predictable style throughout the site*p*': 'Enfin, j\'ai dû affiner mes sélecteurs CSS pour éviter les conflits inattendus dus à l\'héritage et à la cascade. En approfondissant mes connaissances sur la spécificité CSS, j\'ai réussi à créer un style cohérent et prévisible sur l\'ensemble du site.',
};

export default FR;


/*
const FR = {
  fr: 'Français',
  ...
};

Peux-tu me garder les clés (attributs) de ce JSON et me traduire les clés en Espagnol ?
Si des valeurs sont entre accolades "{" ne les traduit pas et laisses les telles quelles !
*/